name: Lint
on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.6.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
